# cmake/VexSanitizers.cmake

if(VEX_ENABLE_ASAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address)
        message(STATUS "VEX: AddressSanitizer enabled")
    else()
        message(WARNING "ASAN not supported on this compiler")
    endif()
endif()

if(VEX_ENABLE_UBSAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options(-fsanitize=undefined)
        add_link_options(-fsanitize=undefined)
        message(STATUS "VEX: UBSanitizer enabled")
    endif()
endif()

if(VEX_ENABLE_TSAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options(-fsanitize=thread)
        add_link_options(-fsanitize=thread)
        message(STATUS "VEX: ThreadSanitizer enabled")
    endif()
endif()

if(VEX_ENABLE_MSAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        add_compile_options(-fsanitize=memory -fno-omit-frame-pointer)
        add_link_options(-fsanitize=memory)
        message(STATUS "VEX: MemorySanitizer enabled")
    else()
        message(WARNING "MSAN only supported with Clang")
    endif()
endif()

if(VEX_ENABLE_COVERAGE)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options(--coverage -fprofile-arcs -ftest-coverage)
        add_link_options(--coverage)
        message(STATUS "VEX: Coverage instrumentation enabled")
    endif()
endif()